#!/usr/bin/env python3
"""charts — draw a CSV. Four shapes, two surfaces, no knowledge of your report.

    report-kit charts --format                   the CSV format, frozen
    report-kit charts new --kind waterfall       charts/waterfall.csv to fill, and its entry
    report-kit charts --check charts/*.csv       is this drawable
    report-kit charts charts/failover.csv --kind line --mark-x 20 primary lost
    report-kit charts charts/floor.csv --kind parts --theme navy
    report-kit charts --all                      every chart in charts/charts.yaml
    report-kit charts --check                    the spec, stale SVGs, missed CSVs

What goes on which axis comes from the file. The shape is the one thing the data
cannot say, so `--kind` says it. Worked files for every shape are under
`examples/tenant-platform/`; why a chart CSV may hold what it holds is `formats.md`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .canvas import (DEFAULT_THEMES, configure, load_backend, load_themes,
                     svg_name)
from .errors import ChartError, Skip
from .kinds import KINDS, NO_AXIS, Marks
from .spec import CHART_DIR, SPEC, Entry, checked, read_spec
from .table import read, sha256, with_axis

EXIT_OK = 0
EXIT_FAILED = 1
EXIT_USAGE = 2

DRAWN_KEYS = ("kind", "rule", "mark_x", "points")
STAMP = "<!-- generated by report-kit charts from {source}: edit the CSV, not this file -->"

FORMAT = """\
the format
  line 1   column names
  line 2   a unit for every column, always
  line 3+  the data

  tier,compute,database,standby
  label,$/tenant/month,$/tenant/month,$/tenant/month aside
  pro,12,8,6

what the units row decides
  label        this column names the points; it is not drawn as a series
  anything     a unit. Columns sharing one share a panel, or a stack
  "<u> aside"  its own bar beside the stack, not inside it (--kind bars)

what the file decides on its own
  the x axis   the first numeric column that is not a label
  log scales   an axis wider than 25x goes log, and y follows x past 10x
  a subtotal   a waterfall row restating the running total
  a gap        an empty cell; a line breaks there rather than bridging it

  Put only what is drawn in the file. A column kept for a caption becomes a
  panel nobody wanted.

the four shapes
  line       one panel per unit on a shared x axis
  bars       stacked bars per step, with an ` aside` unit beside them
  parts      one horizontal bar: the rows are the parts, there is no axis
  waterfall  ordered steps, each starting where the last ended

what a table cannot carry, on --kind line only
  --rule 300 p99 target            a horizontal threshold line
  --mark-x 100 break-even          a vertical line at one x, on every panel
  --points                         the marks without the line joining them,
                                   for points that are not a sequence

charts/charts.yaml, one entry per chart, so a report renders with one command
  failover:                        draws charts/failover.csv
    kind: line
    rule: {at: 300, text: p99 target}
    mark_x: {at: 20, text: primary lost}
    points: false
  floor:
    kind: parts

  --all draws every entry on every theme. --check with no file named fails on
  an entry it cannot draw, a CSV no entry names, and an SVG older than its CSV
  or its entry, so a stale picture cannot reach the report.
"""

EPILOG = """\
output
  charts/<name>.svg beside charts/<name>.csv, plus -navy for the second
  surface, and manifest-<theme>.json recording which CSV and flags made each
  SVG. Every SVG says in its first lines that it is generated. --all owns the
  SVGs in its output directory: one no entry produces is deleted, so keep
  hand-drawn images elsewhere.

  Each SVG is authored at 1620 x 1000 units, so a font size is a pixel on an
  1800px slide and scales down to an article without dropping below a readable
  label. Text stays text, so the fonts resolve wherever the file is opened.

themes
  --theme light | navy, or a name in charts/themes.json, which holds the same
  keys as the defaults and overrides a theme or adds one.

three rules the renderer does not let you override
  No chart carries two y-scales: a second unit goes in a second panel sharing
  the x axis, because two scales on one frame let the author choose where the
  lines cross. Series colours are steps of one hue ordered by magnitude, so
  adjacent segments stay apart for a colour-blind reader. And no label sits at a
  fixed offset: every one is measured against the frame and against what is
  already placed.

  So change the CSV rather than the renderer.
"""

SKELETON = {
    "line": "point,x,measure,cost\nlabel,x unit,measure unit,$\nfirst,1,10,100\n",
    "bars": "step,part_a,part_b,spare\nlabel,$,$,$ aside\nfirst,1.0,2.0,4.0\n",
    "parts": "part,amount\nlabel,$/month\nfirst,100\n",
    "waterfall": "step,amount\nlabel,$\ngross,10\nless something,-2\nnet,8\n",
}


def cmd_format() -> int:
    print(FORMAT)
    return EXIT_OK


def cmd_new(kind: str) -> int:
    if kind not in SKELETON:
        raise ChartError(f"unknown kind {kind!r} — have {', '.join(KINDS)}")
    path = CHART_DIR / f"{kind}.csv"
    if path.exists():
        print(f"{path} already exists, left alone")
        return EXIT_OK
    CHART_DIR.mkdir(exist_ok=True)
    path.write_text(SKELETON[kind], encoding="utf-8")
    with SPEC.open("a", encoding="utf-8") as spec:
        spec.write(f"{path.stem}:\n  kind: {kind}\n")
    print(path)
    print(f"{SPEC}: + {path.stem}")
    return EXIT_OK


def inspect(path: Path, kind: str | None) -> tuple[list[str], list[str]]:
    """(problems, notes). A problem means the file cannot be drawn."""
    try:
        data = read(path)
    except Skip as exc:
        return [f"{path.name}: {exc}"], []
    notes = [f"{path.name}: {data.rows} rows, {len(data.labels)} label column(s), "
             f"{len(data.groups)} unit group(s)"]
    if kind is None or kind in NO_AXIS:
        return [], notes
    try:
        with_axis(data)
    except Skip as exc:
        return [f"{path.name}: {exc}"], notes
    return [], notes


def report(problems: list[str], notes: list[str], files: int) -> int:
    for line in problems:
        print(line)
    for line in notes:
        print(f"note: {line}")
    print(f"\n{len(problems)} problem(s) across {files} file(s)")
    return EXIT_FAILED if problems else EXIT_OK


def cmd_check(paths: list[Path], kind: str | None) -> int:
    problems, notes = [], []
    for path in paths:
        found, said = inspect(path, kind)
        problems.extend(found)
        notes.extend(said)
    return report(problems, notes, len(paths))


def add_mark_flags(p: argparse.ArgumentParser) -> None:
    p.add_argument("--rule", nargs="+", metavar=("VALUE", "TEXT"),
                   help="a threshold line, e.g. --rule 300 p99 target")
    p.add_argument("--mark-x", nargs="+", metavar=("VALUE", "TEXT"),
                   help="a vertical line at one x, e.g. --mark-x 100 break-even")
    p.add_argument("--points", action="store_true",
                   help="draw the marks without joining them")


def marks_record(marks: Marks) -> dict:
    record = {"rule": marks.rule, "mark_x": marks.mark_x,
              "points": not marks.join}
    return {key: value for key, value in record.items() if value}


def write_manifest(out: Path, theme_name: str, fresh: list[dict],
                   replace: bool) -> None:
    """A single call merges, because each kind is its own call. `--all` drew
    everything, so it replaces, and a chart dropped from the spec leaves."""
    if not fresh:
        return
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"manifest-{theme_name}.json"
    kept = ([] if replace or not path.exists()
            else json.loads(path.read_text(encoding="utf-8")))
    drawn = {entry["svg"] for entry in fresh}
    merged = sorted([e for e in kept if e["svg"] not in drawn] + fresh,
                    key=lambda entry: entry["svg"])
    path.write_text(json.dumps(merged, indent=2) + "\n", encoding="utf-8")
    print(path)


def stamp(svg: Path, source: Path) -> None:
    head, _, body = svg.read_text(encoding="utf-8").partition("\n")
    svg.write_text(f"{head}\n{STAMP.format(source=source.name)}\n{body}",
                   encoding="utf-8")


def draw(entry: Entry, theme_name: str, theme: dict, out: Path) -> list[dict]:
    written = KINDS[entry.kind](read(entry.path), theme, out, theme_name,
                                entry.marks)
    for svg in written:
        stamp(svg, entry.path)
        print(svg)
    return [{"svg": svg.name, "kind": entry.kind, "theme": theme_name,
             **marks_record(entry.marks), "source": str(entry.path),
             "source_sha256_12": sha256(entry.path)} for svg in written]


def render(entries: list[Entry], theme_name: str, theme: dict, out: Path,
           replace: bool) -> None:
    load_backend()
    configure(theme)
    manifest, skipped = [], []
    for entry in entries:
        try:
            manifest.extend(draw(entry, theme_name, theme, out))
        except Skip as exc:
            skipped.append(f"{entry.path.name}: {exc}")
    write_manifest(out, theme_name, manifest, replace)
    for line in skipped:
        print(f"skipped — {line}", file=sys.stderr)


def cmd_render(entries: list[Entry], theme_name: str, themes: dict,
               out: Path) -> int:
    render(entries, theme_name, themes[theme_name], out, replace=False)
    return EXIT_OK


def chart_of(svg: Path, themes: dict) -> str:
    for name in themes:
        if svg.stem.endswith(f"-{name}"):
            return svg.stem[:-len(name) - 1]
    return svg.stem


def prune(out: Path, entries: list[Entry], themes: dict) -> None:
    named = {entry.path.stem for entry in entries}
    for svg in sorted(out.glob("*.svg")):
        if chart_of(svg, themes) not in named:
            svg.unlink()
            print(f"removed {svg}, which no entry of {SPEC.name} draws")


def cmd_all(theme_names: list[str], themes: dict, out: Path) -> int:
    entries = read_spec()
    for name in theme_names:
        render(entries, name, themes[name], out, replace=True)
    prune(out, entries, themes)
    return EXIT_OK


def manifests(out: Path) -> dict:
    return {path.stem[len("manifest-"):]: json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(out.glob("manifest-*.json"))}


def staleness(entry: Entry, theme_name: str, records: list, out: Path):
    svg = svg_name(entry.name, theme_name)
    record = next((r for r in records if r["svg"] == svg), None)
    if record is None or not (out / svg).exists():
        return f"{entry.name}: not drawn on {theme_name} — run --all"
    if not entry.path.exists():
        return None
    if record["source_sha256_12"] != sha256(entry.path):
        return f"{entry.name}: {entry.path.name} changed since {svg} was drawn — run --all"
    drawn = {key: record[key] for key in DRAWN_KEYS if key in record}
    wanted = json.loads(json.dumps({"kind": entry.kind,
                                    **marks_record(entry.marks)}))
    if drawn != wanted:
        return f"{entry.name}: {SPEC.name} changed since {svg} was drawn — run --all"
    return None


def stale(entries: list[Entry], out: Path) -> list[str]:
    drawn = manifests(out)
    if not drawn:
        return [f"nothing drawn yet in {out}/ — run --all"]
    return [line for theme_name, records in drawn.items() for entry in entries
            if (line := staleness(entry, theme_name, records, out))]


def cmd_check_spec() -> int:
    entries = read_spec()
    named = {entry.path.resolve() for entry in entries}
    problems, notes = [], []
    for entry in entries:
        found, said = inspect(entry.path, entry.kind)
        problems.extend(found)
        notes.extend(said)
    problems.extend(f"{path.name}: no entry in {SPEC.name}, so --all never draws it"
                    for path in sorted(CHART_DIR.glob("*.csv"))
                    if path.resolve() not in named)
    problems.extend(stale(entries, CHART_DIR))
    return report(problems, notes, len(entries))


def parse_mark(flag: str, given: list[str] | None):
    if not given:
        return None
    value, *text = given
    try:
        return float(value), " ".join(text)
    except ValueError as exc:
        raise ChartError(f"{flag} wants a number first, got {value!r}") from exc


def build_marks(kind: str | None, opts) -> Marks:
    return checked(kind, Marks(rule=parse_mark("--rule", opts.rule),
                               mark_x=parse_mark("--mark-x", opts.mark_x),
                               join=not opts.points))


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="report-kit charts", description=__doc__, epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("csv", nargs="*", type=Path,
                   help="one or more CSVs, or the word `new`")
    p.add_argument("--kind", choices=list(KINDS), help="which shape to draw")
    p.add_argument("--out", type=Path,
                   help=f"where the SVGs go (default {CHART_DIR}/, beside the CSVs)")
    p.add_argument("--theme",
                   help=f"{' or '.join(DEFAULT_THEMES)}, or a name from "
                        f"charts/themes.json (default light; every theme "
                        f"with --all)")
    add_mark_flags(p)
    p.add_argument("--all", action="store_true",
                   help=f"draw every chart {SPEC} names")
    p.add_argument("--check", action="store_true",
                   help="say whether each CSV is drawable; draw nothing. "
                        f"With no CSV, check {SPEC} and whether each SVG is "
                        f"current")
    p.add_argument("--format", action="store_true",
                   help="print the CSV format and exit")
    return p


def chosen_themes(opts, every: bool) -> tuple[list[str], dict]:
    themes = load_themes(Path("."))
    if opts.theme is None:
        return (list(themes) if every else ["light"]), themes
    if opts.theme not in themes:
        raise ChartError(f"unknown theme {opts.theme!r} — have "
                         f"{', '.join(sorted(themes))}")
    return [opts.theme], themes


def run_all(opts) -> int:
    if opts.csv or opts.kind or opts.rule or opts.mark_x or opts.points:
        raise ChartError(f"--all takes its files, kinds and marks from {SPEC}")
    names, themes = chosen_themes(opts, every=True)
    return cmd_all(names, themes, opts.out or CHART_DIR)


def run_named(opts) -> int:
    if not opts.kind:
        raise ChartError(f"--kind is the one thing the file cannot say — "
                         f"{', '.join(KINDS)}")
    names, themes = chosen_themes(opts, every=False)
    marks = build_marks(opts.kind, opts)
    entries = [Entry(path, opts.kind, marks) for path in opts.csv]
    return cmd_render(entries, names[0], themes, opts.out or CHART_DIR)


def main(argv: list[str] | None = None) -> int:
    opts = build_parser().parse_args(argv)
    try:
        if opts.format:
            return cmd_format()
        if opts.csv and str(opts.csv[0]) == "new":
            if not opts.kind:
                raise ChartError("new needs --kind")
            return cmd_new(opts.kind)
        if opts.all:
            return run_all(opts)
        if opts.check:
            return (cmd_check(opts.csv, opts.kind) if opts.csv
                    else cmd_check_spec())
        if not opts.csv:
            raise ChartError("name at least one CSV, or --all, or --format")
        return run_named(opts)
    except ChartError as exc:
        print(f"{exc}", file=sys.stderr)
        return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
