"""The first lines of every SVG: where it came from, and what it was drawn with."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from .kinds import Marks
from .table import sha256

STAMP = ("<!-- generated by report-kit charts from {source} "
         "(csv {csv}, spec {spec}): edit the CSV, not this file -->")
READ = re.compile(r"<!-- generated by report-kit charts from \S+ "
                  r"\(csv ([0-9a-f]{12}), spec ([0-9a-f]{12})\)")
HEAD_LINES = 3


def spec_hash(kind: str, marks: Marks, colours: dict) -> str:
    drawn = {"kind": kind, "rule": marks.rule, "mark_x": marks.mark_x,
             "join": marks.join, "theme": colours}
    text = json.dumps(drawn, sort_keys=True)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def write(svg: Path, source: Path, kind: str, marks: Marks,
          colours: dict) -> None:
    head, _, body = svg.read_text(encoding="utf-8").partition("\n")
    line = STAMP.format(source=source.name, csv=sha256(source),
                        spec=spec_hash(kind, marks, colours))
    svg.write_text(f"{head}\n{line}\n{body}", encoding="utf-8")


def read(svg: Path) -> tuple[str, str] | None:
    """(csv hash, spec hash) from the stamp, or None for an SVG without one."""
    with svg.open(encoding="utf-8") as handle:
        head = "".join(handle.readline() for _ in range(HEAD_LINES))
    found = READ.search(head)
    return found.groups() if found else None
